apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-b1zs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-b1zs@sha256:8e52da733ed5156530e2c85e9a69fde0e83923e0d1b4e2e274e9e9e279ea5e7f
        name: my-nodejs
        resources: {}
status: {}
